language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  # - "pypy" - won't work as smmap doesn't work (see gitdb/.travis.yml for details)
matrix:
  allow_failures:
    - python: "2.6"
git:
  # a higher depth is needed for most of the tests - must be high enough to not actually be shallow
  # as we clone our own repository in the process
  depth: 99999
install:
  - git submodule update --init --recursive
  - git fetch --tags
  - pip install coveralls flake8 sphinx

  # generate some reflog as git-python tests need it (in master)
  - git tag __testing_point__
  - git checkout master || git checkout -b master
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard __testing_point__

  # as commits are performed with the default user, it needs to be set for travis too
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis Runner"
  # If we rewrite the user's config by accident, we will mess it up
  # and cause subsequent tests to fail
  - cat git/test/fixtures/.gitconfig >> ~/.gitconfig
script:
  # Make sure we limit open handles to see if we are leaking them
  - ulimit -n 96
  - ulimit -n
  - nosetests -v --with-coverage
  - flake8
  - cd doc && make html
after_success:
  - coveralls
