language: erlang
#python:
#  - "2.6"
#  - "2.7"
#  - "3.3"
#  - "3.4"
#  # - "pypy" - won't work as smmap doesn't work (see gitdb/.travis.yml for details)
env:
 global:
  - NEURODEBIAN=1  # I have generated chroots only for neurodebian-enabled everything
 matrix:
  # Do not be greedy and enable all at once -- free public services
  # might start puking into your face.  Select known to
  # fail/representative set:
  #- DIST= REL= ARCH=
  #- DIST=debian REL=wheezy ARCH=i386
  - DIST=debian REL=wheezy ARCH=amd64
  - DIST=debian REL=jessie ARCH=i386
  #- DIST=debian REL=jessie ARCH=amd64
  #- DIST=debian REL=sid ARCH=i386
  - DIST=debian REL=sid ARCH=amd64 COVERAGE=1
  #- DIST=ubuntu REL=precise ARCH=i386
  - DIST=ubuntu REL=precise ARCH=amd64
  #- DIST=ubuntu REL=saucy ARCH=i386
  #- DIST=ubuntu REL=saucy ARCH=amd64
  #- DIST=ubuntu REL=trusty ARCH=i386
  - DIST=ubuntu REL=trusty ARCH=amd64
git:
  # a higher depth is needed for most of the tests - must be high enough to not actually be shallow
  # as we clone our own repository in the process
  depth: 99999
install:
  - git submodule update --init --recursive
  - git fetch --tags
  - pip install coveralls flake8 sphinx

  # generate some reflog as git-python tests need it (in master)
  - git tag __testing_point__
  - git checkout master
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard HEAD~1
  - git reset --hard __testing_point__

  # as commits are performed with the default user, it needs to be set for travis too
  - git config --global user.email "travis@ci.com"
  - git config --global user.name "Travis Runner"
  - wget -q http://neuro.debian.net/travis-chroot && chmod +x travis-chroot
  - ./travis-chroot prepare # before ulimit hits hard ;-)
  - ./travis-chroot run pip install -r test-requirements.txt
script: 
  # Make sure we limit open handles to see if we are leaking them
  - ulimit -n 96
  - ulimit -n
  - ./travis-chroot run nosetests -v --with-coverage
  - flake8
  - cd doc && make html
after_success:
  - coveralls
